### ISSUE TITLE
ImageBufAlgo.ociodisplay supported?

### ISSUE THREAD

**Issue by simonreeves** [fredrikaverpil/oiio-python#40]
Hello there,

I am trying to convert exrs to jpg and am constantly getting the error: `Could not construct the color transform`

I have tried based on the examples here, using spi-vfx as a guide but really I want to be using aces
https://openimageio.readthedocs.io/en/latest/pythonbindings.html

I think first question I should ask is this built with `OCIO`? Im just trying to find a solution to maintain an OCIO look in a 8bit format like jpg without going into nuke for example!

**Comment by fredrikaverpil** [comment]
No, sorry, it is not:
https://github.com/fredrikaverpil/oiio-python/blob/67ed4e3ebf7e004b7334e0d2f9f05fb0e611bd39/src/vcpkg/ports/openimageio-py3.6/portfile.cmake#L63

**Comment by simonreeves** [comment]
Thanks anyway. I could still use the other features potentially!
I have also found a windows binary that works for me http://www.nico-rehberg.de/tools.html
